language: common-lisp

branches:
  only:
    - master
    - /^ci-.*$/

env:
  global:
    - PATH=~/.roswell/bin:$PATH
  jobs:
    - LISP=sbcl-bin/2.0.3 # AtCoder
    - LISP=sbcl-bin/1.5.5 # yukicoder
    - LISP=sbcl-bin/1.4.16 # CS Academy
    - LISP=sbcl-bin/1.3.13 # CodeChef

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - git clone --depth=1 -b release https://gitlab.common-lisp.net/asdf/asdf.git ~/lisp/asdf

script:
  - ros -s fiveam -e '(ql:quickload :cp/test)
                      (or (fiveam:run! (quote cp/test/base:base-suite))
                          (uiop:quit 1))'
