name: CI

on: [push]

jobs:
  test:
    name: ${{ matrix.lisp }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lisp: [sbcl-bin/2.0.3, sbcl-bin/1.5.5, sbcl-bin/1.3.13, sbcl-bin/1.3.1]

    steps:
      - uses: actions/checkout@v1
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          ROSWELL_LATEST_ASDF=1
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install fiveam
        run: ros install fiveam
      - name: Run tests
        run: |
          ros -s fiveam -e '(ql:quickload :cp/test)
                            (or (fiveam:run! (quote cp/test/base:base-suite))
                                (uiop:quit 1))'
